### ISSUE TITLE
What is the sp2id in pre-train?

### ISSUE THREAD

**Issue by JaistZhanhangZhang** [KunZhou9646/seq2seq-EVC#10]
Hello Zhoukun,
I used VCTK-dataset for pre-train,
In reader.py

 ```
class TextMelIDLoader 
get_text_mel_id_pair(self, path)
speaker_id = [self.sp2id[speaker_id]]
```

However, in function __init__
`self.sp2id={'Neutral':0,'Happy':1,'Sad':2,'Angry':3,'Surprise':4}`
I think we do not have emotion label for pre-train, using VCTK, do we?
I changed it to the speaker id, like "p225","p226" which contained in VCTK-datasets,
but the training loss is always NaN.
except this, I only changed the dir of datasets.
Is there anything I have missed?

**Comment by KunZhou9646** [comment]
Hey, you should use pre-train folder to conduct the pretrain. You don't need emotion labels, and you only need the speaker labels. BTW, I have provided the pre-trained weights with VCTK and you can directly perform emotion training.

**Comment by JaistZhanhangZhang** [comment]
Well, I mean, there is a [Key Error] when runing the code, causing by sp2id. Is that a bug?
Should I rewrite it  ?

**Comment by KunZhou9646** [comment]
Could you please show me the bug?

**Comment by JaistZhanhangZhang** [comment]
OK, I will record all bugs I faced, but may take some time.. I will put it later.

**Comment by KunZhou9646** [comment]
Thanks! Just would like to check is there any bugs during emotion training (Stage II) as well?

**Comment by JaistZhanhangZhang** [comment]
OK, After stage I, I will try  emotion training, then record bugs. Thank you !

**Comment by JaistZhanhangZhang** [comment]
After I change the Data params in harames

1:
```
File "seq2seq-EVC-main/pre-train/logger.py", line 5, in <module>  
   from plotting_utils import plot_alignment_to_numpy, plot_spectrogram_to_numpy, plot_alignment ModuleNotFoundError: No module named 'plotting_utils' 
``` 

I copy '_plotting_utils.py_' from "Non-parallel Speaker Voice Conversion : [](https://github.com/jxzhanggg/nonparaSeq2seqVC_code)

2:
`RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at ../aten/src/THC/THCGeneral.cpp:50
`
I changed the code in train.py:
`os.environ['CUDA_VISIBLE_DEVICES'] = '2'`
to
`os.environ['CUDA_VISIBLE_DEVICES'] = '0'`

3:
```
Traceback (most recent call last):
  File "train.py", line 374, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 215, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 53, in prepare_dataloaders
    trainset = TextMelIDLoader(hparams.training_list, hparams.mel_mean_std)
TypeError: __init__() missing 2 required positional arguments: 'speaker_A' and 'speaker_B'
```

I read the code of class TextMelIDLoade __init__(), finding that 'speaker_A' and 'speaker_B' has not been used, thus I changed the __init__ function:

from
`def __init__(self, list_file, mean_std_file, speaker_A, speaker_B,shuffle=True, pids=None)`
to
`def __init__(self, list_file, mean_std_file,shuffle=True, pids=None)`

4:
```
Traceback (most recent call last):
  File "train.py", line 374, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 215, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 53, in prepare_dataloaders
    trainset = TextMelIDLoader(hparams.training_list, hparams.mel_mean_std)
  File "seq2seq-EVC-main/pre-train/reader/reader.py", line 46, in __init__
    path, n_frame = line.strip().split()
ValueError: too many values to unpack (expected 2)
```

the training_mel_list and test_mel_list which is generated by "generated_list_mel.py" is like
/VCTK-Corpus/mel/p225/p225_122.mel.npy 105 21

I change the code into
`path, n_frame , _ = line.strip().split()`

5:
```
Traceback (most recent call last):
  File "train_copy", line 374, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train_copy", line 215, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train_copy", line 53, in prepare_dataloaders
    trainset = TextMelIDLoader(hparams.training_list, hparams.mel_mean_std)
  File "seq2seq-EVC-main/pre-train/reader/reader.py", line 52, in __init__
    if not speaker_id in pids:
TypeError: argument of type 'NoneType' is not iterable
```

Since 
`def __init__(self, list_file, mean_std_file, speaker_A, speaker_B,shuffle=True, pids=None)`
pids = None,
I don't know how to fix this

**Comment by KunZhou9646** [comment]
I have updated read.py. Could you retry the codes and let me know if the issue still exists? thanks!

**Comment by JaistZhanhangZhang** [comment]
well, have you update train.py? I think problems 1,2,3,4 still exist...

**Comment by KunZhou9646** [comment]
Oh I thought you already fixed 1,2,3,4. I am aiming at sovling problem 5. I will update 1,2,3,4 later. But do let me know if #5 sloves.

**Comment by JaistZhanhangZhang** [comment]
Yes these problems have solved, however other problems appeared
```
Traceback (most recent call last):
  File "train.py", line 377, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 257, in train
    if epoch > hparams.warmup:
AttributeError: 'HParams' object has no attribute 'warmup'
```

other errors I will test later

**Comment by JaistZhanhangZhang** [comment]
Original Traceback (most recent call last):
  File "/seq2seq-EVC-main/pre-train/reader/reader.py", line 135, in __getitem__
    return self.get_text_mel_id_pair(self.file_path_list[index])
  File "/seq2seq-EVC-main/pre-train/reader/reader.py", line 105, in get_text_mel_id_pair
    text_input = self.get_text(text_path)
  File "/seq2seq-EVC-main/pre-train/reader/reader.py", line 122, in get_text
    text = read_text(text_path)
  File "/seq2seq-EVC-main/pre-train/reader/reader.py", line 27, in read_text
    with open(fn) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhoukun/nonparaSeq2seqVC_code-master/0013/txt/p245_259.phones'

0013 which I downloaded don't have a ".phones" files. I don't know how to change the code.
Do you mean that using the ".phones" files which are generated from VCTK-Corpus?

**Comment by KunZhou9646** [comment]
Sorry for the inconvenience. I think I might mess up with some files with Stage II. Could you directly perform Stage II Emotion Training with the pre-trained weights from Stage I? I have tested Stage II and Conversion stage on my side previously. I will figure this out soon.

**Comment by JaistZhanhangZhang** [comment]
OK, I see. I will try Stage II .

**Comment by JaistZhanhangZhang** [comment]
Some dir Error in  "generate_list_mel.py" which is in Fine-turn
```
Traceback (most recent call last):
  File "generate_list_mel.py", line 34, in <module>
    for seen_speaker in os.listdir('/data07/zhoukun/VCTK-Corpus/mel'):
FileNotFoundError: [Errno 2] No such file or directory: '/data07/zhoukun/VCTK-Corpus/mel'
```

Which dir should I change here, ESD datasets or VCTK-Corpus datasets dir?
If use ESD datasets, it can only generate text like 
`/Emotional Speech Dataset (ESD)/0008/Surprise`
which can not find .wav or .phones files

**Comment by JaistZhanhangZhang** [comment]
Well, I have tried the fine-turn step, However the loss is still NaN
```
Validation loss 1800: TTS       nan  VC       nan                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1350: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.                                 
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")                                                                                               
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor.                                                                                                                                                
NaN or Inf found in input tensor. 
```
[step-1800-vc.pdf](https://github.com/KunZhou9646/seq2seq-EVC/files/9630211/step-1800-vc.pdf)
I attach a pdf which is  in ali.
Is that normal?

**Comment by JaistZhanhangZhang** [comment]
Hello, there are still some errors I do not understand.
```
Traceback (most recent call last):
  File "train.py", line 394, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 266, in train
    checkpoint_path, model, optimizer_main, optimizer_sc)
  File "train.py", line 118, in load_checkpoint
    model.load_state_dict(checkpoint_dict['state_dict'])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Parrot:
        size mismatch for speaker_encoder.projection2.linear_layer.weight: copying a param with shape torch.Size([99, 128]) from checkpoint, the shape in current model is torch.Size([4, 128]).
        size mismatch for speaker_encoder.projection2.linear_layer.bias: copying a param with shape torch.Size([99]) from checkpoint, the shape in current model is torch.Size([4]).
        size mismatch for speaker_classifier.projection.linear_layer.weight: copying a param with shape torch.Size([99, 512]) from checkpoint, the shape in current model is torch.Size([4, 512]).
        size mismatch for speaker_classifier.projection.linear_layer.bias: copying a param with shape torch.Size([99]) from checkpoint, the shape in current model is torch.Size([4]).
```

**Comment by KunZhou9646** [comment]
Because the model is trained with 99 speakers in Stage I and fine-tuned with 4 emotions in Stage II.

**Comment by JaistZhanhangZhang** [comment]
Yes I think so. But How should I change the output dimentional of pre-train model ?

**Comment by KunZhou9646** [comment]
def warm_start_model(checkpoint_path, model):
    assert os.path.isfile(checkpoint_path)
    print(("Warm starting model from checkpoint '{}'".format(checkpoint_path)))
    checkpoint_dict = torch.load(checkpoint_path, map_location='cpu')
    new_state_dict = {}
    new_state_dict = {}
    for k, v in checkpoint_dict['state_dict'].items():
        if k not in ['speaker_encoder.projection2.linear_layer.weight',
                     'speaker_encoder.projection2.linear_layer.bias',
                     'speaker_classifier.projection.linear_layer.weight',
                     'speaker_classifier.projection.linear_layer.bias']:
            new_state_dict[k] = v
        else:
            s = v.size()
            if len(s) == 2:
                new_state_dict[k] = torch.nn.init.normal_(torch.empty((4, s[1])))
            else:
                new_state_dict[k] = torch.nn.init.normal_(torch.empty(4))
            #new_state_dict[k].weight.requires_grad = False
            #new_state_dict[k].bias.requires_grad = False

    model.load_state_dict(new_state_dict,strict=False)
    #model.load_state_dict(torch.load(checkpoint_path)['state_dict'], strict=False)
    return model

I think I already fixed this in my codes. (fine-tune/train.py)

**Comment by JaistZhanhangZhang** [comment]
My fault. My fine-tune is successful. I think there are no errors in fine-tune. Thanks!

**Comment by JaistZhanhangZhang** [comment]
OK, I solved all problems. Thank you very much !

**Comment by TengNN** [comment]
> OK, I solved all problems. Thank you very much !
hello
I have some questions I'd like to ask you
How should I define my optimizer?
![image](https://github.com/user-attachments/assets/b2da0cf8-550c-4877-824e-1bbb4a619715)
in pre-train/train;line297
