### ISSUE TITLE
some quickstart

### ISSUE THREAD

**Issue by Rongjiehuang** [KunZhou9646/seq2seq-EVC#2]
Hi, author:
         Nice implementation! I'm researching adaptive TTS (speaker and emotion) and getting inspired by your work. Could you please provide some files (e.g., training/valid_list and embeddings) for experiment quickstart? Thanks!

**Comment by felixkreuk** [comment]
I thank the authors for the implementation as well.
I would also love for some quick-start guide regarding the data preprocessing.

**Comment by KunZhou9646** [comment]
Thank you for your interest in our work! I have updated the codes:
1/ add training/valid_list for pre-train and fine-tune. You can find them in the reader file;
2/ add the data preprocessing instruction.

**Comment by felixkreuk** [comment]
Thanks @KunZhou9646, can you please describe in what format you expect the data to be structured for the fine-tuning phase?

**Comment by KunZhou9646** [comment]
Assume that you already got ESD dataset :)

You can choose a speaker ('0013') from ESD, I just upload a file named "0013". You should save the training data in that file.

1/ mel: save for mel files;
2/ text: save for text files (ESD provides and I upload here);
3/ wav: follow the train/valid/test in ESD
