### ISSUE TITLE
AttributeError: 'HParams' object has no attribute 'speaker_A'

### ISSUE THREAD

**Issue by felixkreuk** [KunZhou9646/seq2seq-EVC#3]
Hello,

Thanks for you this implementation and interesting work.
When I tried to run your code, I came across the following exception:
```
Traceback (most recent call last):
  File "train.py", line 378, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 238, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 55, in prepare_dataloaders
    hparams.speaker_A, hparams.speaker_B, pids=None)
AttributeError: 'HParams' object has no attribute 'speaker_A'
```
Upon inspection, it seems that the function `prepare_dataloaders` in `pre-train/train.py` is calling `TextMelIDLoader` constructor with a hyperparameter named `speaker_A` but it doesn't exist in `hparams.py`.
Internally, it seems that `TextMelIDLoader` doesn't use this argument.

Also, it seems that the `pids` argument to `TextMelIDLoader` is `None` which crashes at this line:
```
    if not speaker_id in pids:
        continue
```

Could you please advise how this should be solved correctly?
Thank you!

**Comment by KunZhou9646** [comment]
Hey, so sorry for the inconvenience. I have updated the codes. 

Btw, I have uploaded the pre-train checkpoints. Feel free to use it and directly go to fine-tune stage. :)

**Comment by felixkreuk** [comment]
Hey, yes I just realized that I'm better off going straight to the fine-tune with your existing checkpoint :) 
Thanks
