### ISSUE TITLE
Style Pre-training .wav files are so noise 

### ISSUE THREAD

**Issue by nguyenviettuan96** [KunZhou9646/seq2seq-EVC#7]
Hi, after we take checkpoint_234000 pre-train on your google driver, we run inference test folder with this checkpoint at first stage. But, unfortunately, these are so noise not clear like original wav. How we can fix that?. Is that better if we change sample rate from 16k to default: 22k?

**Comment by KunZhou9646** [comment]
Hey. Just want to confirm if you did the inference on VCTK corpus. Can you attach some wav files for me to listen?

**Comment by nguyenviettuan96** [comment]
Yes, this .zip file includes your pre-train and my own training, your pre-train is better but not clear like natural human voice
[wave.zip](https://github.com/KunZhou9646/seq2seq-EVC/files/9522719/wave.zip)

**Comment by KunZhou9646** [comment]
If the samples are synthesized with Grinfin-Lim vocoder, then the quality is okay. I use 16kHz as the sampling rate because the ESD dataset is sampled at 16kHz and saved in 16 bits.

**Comment by nguyenviettuan96** [comment]
okay thank you
