### ISSUE TITLE
How can I change the vocoder ?

### ISSUE THREAD

**Issue by nguyenviettuan96** [KunZhou9646/seq2seq-EVC#8]
Hi KunZhou,
Could you give me some answers because I try to make sound voice more clear?
1. Is that your code using Griffin-Lim vocoder?
2. How can I change to neutral vocoder ?
Thank you

**Comment by KunZhou9646** [comment]
1/ This code is using Griffin-Lim vocoder;
2/ You just need to synthesize waveform from the converted mels by using your pre-trained neural vocoders.

**Comment by tranducanhbk** [comment]
Hi KunZhou,
I got the same problem.
Can u tell detail how to change Griffin-Lim vocoder to  neural vocoders in pre-trained

**Comment by KunZhou9646** [comment]
You just need to synthesize the waveform from the mel folder using your neural vocoder.

**Comment by nguyenviettuan96** [comment]
Yes I just have read your other issues and found that your ParallelWaveGAN pretrain  https://drive.google.com/file/d/1n01r7p-XALB6jcI8QGPfX4o9C7JRo6kX/view?usp=sharing . But it is necessary to have config.yaml file to run the model, it would be great if you share it.

**Comment by KunZhou9646** [comment]
[config.pdf](https://github.com/KunZhou9646/seq2seq-EVC/files/9546986/config.pdf)
I enclose my config file here (Please change .pdf to .yml)

**Comment by nguyenviettuan96** [comment]
Thank you you can close this
