### ISSUE TITLE
How to get emotion embedding?

### ISSUE THREAD

**Issue by Scx123** [KunZhou9646/seq2seq-EVC#9]
As shown in README 6.1 `python inference_embedding.py ....`, the code calls `Parrot._initilize_emb` but `_initilize_emb` needs `hparams.a_embedding_path`. How to get `hparams.a_embedding_path`?
Maybe I misunderstood and look forward to your answers!

**Comment by KunZhou9646** [comment]
Hi, first you need to contruct a "zero_embeddings.npy", and all embedding path should be the zero_embedding.py. After you got the emotion embedding, replace the zero_embedding with your emotion embedding. You can find the related comments in hparam.py

**Comment by Scx123** [comment]
Thanks for your reply, the code has been debugged successfully.
